### ISSUE TITLE
v0.1.2 is not marked as the latest release

### ISSUE THREAD

**Issue by alexrp** [Vector35/COMpanion#1]
[v0.1.2](https://github.com/Vector35/COMpanion/releases/tag/0.1.2) has not been marked as the latest release on GitHub. This (I assume) results in [v0.1.1](https://github.com/Vector35/COMpanion/releases/tag/0.1.1) being the latest version available on the official plugins repository. Crucially, that version lacks ea64426, making it unusable. :eyes:

**Comment by alexrp** [comment]
@plafosse ping :eyes:

**Comment by alexrp** [comment]
@psifertex maybe?

**Comment by psifertex** [comment]
Sorry about that, will update it now.

**Comment by psifertex** [comment]
Done.
